import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links: {
    href: string;
    label: string;
  }[] = [
    {
      href: '/',
      label: 'Home',
    },
    {
      href: 'docs',
      label: 'Docs',
    },
    {
      href: '/todos',
      label: 'Todos',
    },
  ];

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header>
          <nav>
            <ul className="flex items-center justify-center gap-5">
              {links.map((link) => (
                <li key={link.href}>
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
